## Module 10 Assignment - Scraping a Website
* Author: brandon chiazza
* version 2.0

In [12]:
from selenium.webdriver.common.by import By
import awscli
import boto3
import selenium
import pandas as pd
import time
from time import sleep
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager


####SCRAPE THE WEBSITE######
###call the webdriver
s=Service(ChromeDriverManager().install())
browser = webdriver.Chrome(service=s)

#enter the url path that needs to be accessed by webdriver
browser.get('https://www.charitiesnys.com/RegistrySearch/search_charities.jsp')

#identify xpath of location to select element
inputElement = browser.find_element(By.XPATH, "/html/body/div/div[2]/div/table/tbody/tr/td[2]/div/div/font/font/font/font/font/font/table/tbody/tr[4]/td/form/table/tbody/tr[2]/td[2]/input[1]")
inputElement.send_keys('0')
inputElement1 = browser.find_element(By.XPATH,"/html/body/div/div[2]/div/table/tbody/tr/td[2]/div/div/font/font/font/font/font/font/table/tbody/tr[4]/td/form/table/tbody/tr[10]/td/input[1]").click()

#identify the table to scrape
table = browser.find_element(By.CSS_SELECTOR,'table.Bordered')
sleep(1)

#####CREATE DATE FRAME#####
#create empty dataframe
df =[]

#loop through dataframe to export table
for row in table.find_elements(By.CSS_SELECTOR,'tr'):
    cols = df.append([cell.text for cell in row.find_elements(By.CSS_SELECTOR,'td')])

df
#update dataframe with header 
df = pd.DataFrame(df, columns = ["Organization Name", "NY Reg #", "EIN" ,"Registrant Type","City","State"])
display(df) #let's have a look at the data before creating the CSV file and loading it into s3

,Organization Name,NY Reg #,EIN,Registrant Type,City,State
0,None,None,None,None,None,None
1,"""Forever Captain Poodaman"" The Ahmad Butler Fo...",48-07-16,843800926,NFP,PHILADELPHIA,PA
2,"""Incredibly Blessed"" Inc",49-54-61,842071758,NFP,STATEN ISLAND,NY
3,"""R"" S.U.C.C.E.S.S. Foundation Inc.",49-06-59,874012670,NFP,ROCHESTER,NY
4,"""Studio 5404"" Inc.",44-39-58,463180470,NFP,MASSAPAQUA,NY
5,"""THEY ARE HAITIAN"" FUND, INC.",20-63-46,300170128,NFP,HUDSON,NY
6,"""Y"" Dive, Inc.",48-45-01,854252095,NFP,SAINT ALBANS,NY
7,(ASMA) American Syrian Multicultural Associati...,42-84-63,273130182,NFP,BROOKLYN,NY
8,#FeedHamburg,48-37-35,854150318,NFP,HAMBURG,NY
9,#HicksStrong Inc.,48-10-48,842612081,NFP,CLIFTON PARK,NY
10,#WalkAway Foundation,47-15-80,832820906,NFP,CARLSBAD,CA
11,04/11 10:17 PM test,47-13-95,206256427,NFP,ALBANY,NY
12,1/20/21 Action Fund,46-99-13,832210730,NFP,SAN FRANCISCO,CA
13,"10/40 Connections, Inc.",45-70-15,621825230,NFP,HIXSON,TN
14,"1000 Feet Project, Inc",45-00-14,473820859,NFP,NEW YORK,NY
15,1000 Islands Hose Haulers,45-38-38,454570241,NFP,CARTHAGE,NY

In [9]:
###LOAD THE FILE INTO S3####
# prepare csv file name   
pathname = 's3://iaseleniumanupam/' #specify location of s3:/{my-bucket}/
filename= 'charities_bureau_scrape_' #name of your group
datetime = time.strftime("%Y%m%d%H%M%S") #timestamp
filenames3 = "%s%s%s.csv"%(pathname,filename,datetime) #name of the filepath and csv file

#load file into s3. Pandas actually leverages boto to connect to s3 and can push the file directly into an s3 bucket
df.to_csv(filenames3, header=True) 

#print success message
print("Successfull uploaded file to location:"+str(filenames3))

Successfull uploaded file to location:s3://iaseleniumanupam/charities_bureau_firstrowblank_20240414211736.csv

<p>There is none in first row so we will again scrape it and remove the first row</p>

In [13]:
from selenium.webdriver.common.by import By
import awscli
import boto3
import selenium
import pandas as pd
import time
from time import sleep
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager


####SCRAPE THE WEBSITE######
###call the webdriver
s=Service(ChromeDriverManager().install())
browser = webdriver.Chrome(service=s)

#enter the url path that needs to be accessed by webdriver
browser.get('https://www.charitiesnys.com/RegistrySearch/search_charities.jsp')

#identify xpath of location to select element
inputElement = browser.find_element(By.XPATH, "/html/body/div/div[2]/div/table/tbody/tr/td[2]/div/div/font/font/font/font/font/font/table/tbody/tr[4]/td/form/table/tbody/tr[2]/td[2]/input[1]")
inputElement.send_keys('0')
inputElement1 = browser.find_element(By.XPATH,"/html/body/div/div[2]/div/table/tbody/tr/td[2]/div/div/font/font/font/font/font/font/table/tbody/tr[4]/td/form/table/tbody/tr[10]/td/input[1]").click()

#identify the table to scrape
table = browser.find_element(By.CSS_SELECTOR,'table.Bordered')
sleep(1)

#####CREATE DATE FRAME#####
#create empty dataframe
df =[]

#loop through dataframe to export table
for row in table.find_elements(By.CSS_SELECTOR,'tr'):
    if row.find_elements(By.XPATH, './parent::thead'):
        continue  # Skip rows within the <thead> section
    cols = df.append([cell.text for cell in row.find_elements(By.CSS_SELECTOR,'td')])

df
#update dataframe with header 
df = pd.DataFrame(df, columns = ["Organization Name", "NY Reg #", "EIN" ,"Registrant Type","City","State"])
display(df) #let's have a look at the data before creating the CSV file and loading it into s3

,Organization Name,NY Reg #,EIN,Registrant Type,City,State
0,"""Forever Captain Poodaman"" The Ahmad Butler Fo...",48-07-16,843800926,NFP,PHILADELPHIA,PA
1,"""Incredibly Blessed"" Inc",49-54-61,842071758,NFP,STATEN ISLAND,NY
2,"""R"" S.U.C.C.E.S.S. Foundation Inc.",49-06-59,874012670,NFP,ROCHESTER,NY
3,"""Studio 5404"" Inc.",44-39-58,463180470,NFP,MASSAPAQUA,NY
4,"""THEY ARE HAITIAN"" FUND, INC.",20-63-46,300170128,NFP,HUDSON,NY
5,"""Y"" Dive, Inc.",48-45-01,854252095,NFP,SAINT ALBANS,NY
6,(ASMA) American Syrian Multicultural Associati...,42-84-63,273130182,NFP,BROOKLYN,NY
7,#FeedHamburg,48-37-35,854150318,NFP,HAMBURG,NY
8,#HicksStrong Inc.,48-10-48,842612081,NFP,CLIFTON PARK,NY
9,#WalkAway Foundation,47-15-80,832820906,NFP,CARLSBAD,CA
10,04/11 10:17 PM test,47-13-95,206256427,NFP,ALBANY,NY
11,1/20/21 Action Fund,46-99-13,832210730,NFP,SAN FRANCISCO,CA
12,"10/40 Connections, Inc.",45-70-15,621825230,NFP,HIXSON,TN
13,"1000 Feet Project, Inc",45-00-14,473820859,NFP,NEW YORK,NY
14,1000 Islands Hose Haulers,45-38-38,454570241,NFP,CARTHAGE,NY

In [14]:
###LOAD THE FILE INTO S3####
# prepare csv file name   
pathname = 's3://iaseleniumanupam/' #specify location of s3:/{my-bucket}/
filename= 'charities_bureau_scrape_20240414211721' #name of your group
datetime = time.strftime("%Y%m%d%H%M%S") #timestamp
filenames3 = "%s%s%s.csv"%(pathname,filename,datetime) #name of the filepath and csv file

#load file into s3. Pandas actually leverages boto to connect to s3 and can push the file directly into an s3 bucket
df.to_csv(filenames3, header=True) 

#print success message
print("Successfull uploaded file to location:"+str(filenames3))

Successfull uploaded file to location:s3://iaseleniumanupam/charities_bureau_scrape_2024041421172120240414212523.csv

<h3>Part 2</h3>

In [18]:
####SCRAPE THE WEBSITE######
#Import libraries
from selenium.common.exceptions import NoSuchElementException, TimeoutException
###call the webdriver
s=Service(ChromeDriverManager().install())
browser = webdriver.Chrome(service=s)

#enter the url path that needs to be accessed by webdriver
browser.get('https://www.charitiesnys.com/RegistrySearch/search_charities.jsp')

#identify xpath of location to select element
inputElement = browser.find_element(By.XPATH, "/html/body/div/div[2]/div/table/tbody/tr/td[2]/div/div/font/font/font/font/font/font/table/tbody/tr[4]/td/form/table/tbody/tr[2]/td[2]/input[1]")
inputElement.send_keys('0')
inputElement1 = browser.find_element(By.XPATH,"/html/body/div/div[2]/div/table/tbody/tr/td[2]/div/div/font/font/font/font/font/font/table/tbody/tr[4]/td/form/table/tbody/tr[10]/td/input[1]").click()


all_page_data= []  # Empty list to store data from each page
while True:
    try:
        next_page = browser.find_element(By.XPATH,'/html/body/div[2]/div/table/tbody/tr/td[3]/div/div/span[2]/a[text()="Next"]')
        sleep(1)
        table = browser.find_element(By.CSS_SELECTOR,'table.Bordered')
        sleep(1)
        for row in table.find_elements(By.CSS_SELECTOR,'tr'):
            if len(row.find_elements(By.CSS_SELECTOR,'td')) != 0:
                all_page_data.append([cell.text for cell in row.find_elements(By.CSS_SELECTOR,'td')])
        next_page.click()
        sleep(4)
    except NoSuchElementException:
        table = browser.find_element(By.CSS_SELECTOR,'table.Bordered')
        sleep(1)
        for row in table.find_elements(By.CSS_SELECTOR,'tr'):
            if len(row.find_elements(By.CSS_SELECTOR,'td')) != 0:
                all_page_data.append([cell.text for cell in row.find_elements(By.CSS_SELECTOR,'td')])
        # Handle the case where "Next" button is not found (reached last page)
        print("Page Ended!")
        break

#update dataframe with header 
df = pd.DataFrame(df, columns = ["Organization Name", "NY Reg #", "EIN" ,"Registrant Type","City","State"])
display(df) #let's have a look at the data before creating the CSV file and loading it into s3

Page Ended!

,Organization Name,NY Reg #,EIN,Registrant Type,City,State
0,"""Forever Captain Poodaman"" The Ahmad Butler Fo...",48-07-16,843800926,NFP,PHILADELPHIA,PA
1,"""Incredibly Blessed"" Inc",49-54-61,842071758,NFP,STATEN ISLAND,NY
2,"""R"" S.U.C.C.E.S.S. Foundation Inc.",49-06-59,874012670,NFP,ROCHESTER,NY
3,"""Studio 5404"" Inc.",44-39-58,463180470,NFP,MASSAPAQUA,NY
4,"""THEY ARE HAITIAN"" FUND, INC.",20-63-46,300170128,NFP,HUDSON,NY
5,"""Y"" Dive, Inc.",48-45-01,854252095,NFP,SAINT ALBANS,NY
6,(ASMA) American Syrian Multicultural Associati...,42-84-63,273130182,NFP,BROOKLYN,NY
7,#FeedHamburg,48-37-35,854150318,NFP,HAMBURG,NY
8,#HicksStrong Inc.,48-10-48,842612081,NFP,CLIFTON PARK,NY
9,#WalkAway Foundation,47-15-80,832820906,NFP,CARLSBAD,CA
10,04/11 10:17 PM test,47-13-95,206256427,NFP,ALBANY,NY
11,1/20/21 Action Fund,46-99-13,832210730,NFP,SAN FRANCISCO,CA
12,"10/40 Connections, Inc.",45-70-15,621825230,NFP,HIXSON,TN
13,"1000 Feet Project, Inc",45-00-14,473820859,NFP,NEW YORK,NY
14,1000 Islands Hose Haulers,45-38-38,454570241,NFP,CARTHAGE,NY

In [19]:
###LOAD THE FILE INTO S3####
# prepare csv file name   
pathname = 's3://iaseleniumanupam/' #specify location of s3:/{my-bucket}/
filename= 'charities_bureau_scrape_All_page_data_' #name of your group
datetime = time.strftime("%Y%m%d%H%M%S") #timestamp
filenames3 = "%s%s%s.csv"%(pathname,filename,datetime) #name of the filepath and csv file

#load file into s3. Pandas actually leverages boto to connect to s3 and can push the file directly into an s3 bucket
df.to_csv(filenames3, header=True) 

#print success message
print("Successfull uploaded file to location:"+str(filenames3))

Successfull uploaded file to location:s3://iaseleniumanupam/charities_bureau_scrape_All_page_data_20240414214911.csv

## References
* https://www.programiz.com/python-programming/working-csv-files
* https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.create_bucket
* https://realpython.com/python-boto3-aws-s3/
* https://robertorocha.info/setting-up-a-selenium-web-scraper-on-aws-lambda-with-python/